### ISSUE TITLE
Problema al registrar Aurora.Network.dll

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum20-server#122]
Intenté hacer el procedimiento via CMD como administrador y salta el siguiente error:

![error_aurora](https://user-images.githubusercontent.com/7727108/181622596-8ee3ffed-72a8-40fe-ad5e-26d7c45aa1e8.jpg)

Windows 10 Pro 21h2 64 bits.

**Comment by morgolock** [comment]
Hola,

Asegurate que tenes todas las dependencias del DLL instaladas.


```
dumpbin /dependents Aurora.Network.dll
Microsoft (R) COFF/PE Dumper Version 14.30.30706.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file Aurora.Network.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    SHELL32.dll
    ole32.dll
    OLEAUT32.dll
    ADVAPI32.dll
    MSVCP140.dll
    WS2_32.dll
    MSWSOCK.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-multibyte-l1-1-0.dll
```

Capaz te falta `VCRUNTIME140.dll` ?

Lo podes instalar de: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by plusin** [comment]
Resuelto, muchas gracias Gulfas!
Instalé: https://aka.ms/vs/17/release/vc_redist.x86.exe y https://aka.ms/vs/17/release/vc_redist.x64.exe

![aurora_resuelto](https://user-images.githubusercontent.com/7727108/181636072-b66a33c3-bc96-4b4e-847c-a43fb3b4deb2.jpg)
